// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMPermission(db *gorm.DB, opts ...gen.DOOption) cRMPermission {
	_cRMPermission := cRMPermission{}

	_cRMPermission.cRMPermissionDo.UseDB(db, opts...)
	_cRMPermission.cRMPermissionDo.UseModel(&model.CRMPermission{})

	tableName := _cRMPermission.cRMPermissionDo.TableName()
	_cRMPermission.ALL = field.NewAsterisk(tableName)
	_cRMPermission.Id = field.NewInt(tableName, "id")
	_cRMPermission.PermissionId = field.NewString(tableName, "permission_id")
	_cRMPermission.PermissionName = field.NewString(tableName, "permission_name")
	_cRMPermission.PermissionURL = field.NewString(tableName, "permission_url")
	_cRMPermission.PermissionType = field.NewInt(tableName, "permission_type")
	_cRMPermission.ParentId = field.NewString(tableName, "parent_id")
	_cRMPermission.Status = field.NewString(tableName, "status")
	_cRMPermission.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMPermission.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMPermission.fillFieldMap()

	return _cRMPermission
}

type cRMPermission struct {
	cRMPermissionDo

	ALL            field.Asterisk
	Id             field.Int    // 主键
	PermissionId   field.String // 业务主键
	PermissionName field.String // 权限名称
	PermissionURL  field.String // 权限URL
	PermissionType field.Int    // 权限类型,1菜单,2按钮,3接口
	ParentId       field.String // 父级id
	Status         field.String // 状态,off禁用,on启用
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMPermission) Table(newTableName string) *cRMPermission {
	c.cRMPermissionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMPermission) As(alias string) *cRMPermission {
	c.cRMPermissionDo.DO = *(c.cRMPermissionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMPermission) updateTableName(table string) *cRMPermission {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.PermissionId = field.NewString(table, "permission_id")
	c.PermissionName = field.NewString(table, "permission_name")
	c.PermissionURL = field.NewString(table, "permission_url")
	c.PermissionType = field.NewInt(table, "permission_type")
	c.ParentId = field.NewString(table, "parent_id")
	c.Status = field.NewString(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMPermission) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.Id
	c.fieldMap["permission_id"] = c.PermissionId
	c.fieldMap["permission_name"] = c.PermissionName
	c.fieldMap["permission_url"] = c.PermissionURL
	c.fieldMap["permission_type"] = c.PermissionType
	c.fieldMap["parent_id"] = c.ParentId
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMPermission) clone(db *gorm.DB) cRMPermission {
	c.cRMPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMPermission) replaceDB(db *gorm.DB) cRMPermission {
	c.cRMPermissionDo.ReplaceDB(db)
	return c
}

type cRMPermissionDo struct{ gen.DO }

type ICRMPermissionDo interface {
	gen.SubQuery
	Debug() ICRMPermissionDo
	WithContext(ctx context.Context) ICRMPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMPermissionDo
	WriteDB() ICRMPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMPermissionDo
	Not(conds ...gen.Condition) ICRMPermissionDo
	Or(conds ...gen.Condition) ICRMPermissionDo
	Select(conds ...field.Expr) ICRMPermissionDo
	Where(conds ...gen.Condition) ICRMPermissionDo
	Order(conds ...field.Expr) ICRMPermissionDo
	Distinct(cols ...field.Expr) ICRMPermissionDo
	Omit(cols ...field.Expr) ICRMPermissionDo
	Join(table schema.Tabler, on ...field.Expr) ICRMPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMPermissionDo
	Group(cols ...field.Expr) ICRMPermissionDo
	Having(conds ...gen.Condition) ICRMPermissionDo
	Limit(limit int) ICRMPermissionDo
	Offset(offset int) ICRMPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMPermissionDo
	Unscoped() ICRMPermissionDo
	Create(values ...*model.CRMPermission) error
	CreateInBatches(values []*model.CRMPermission, batchSize int) error
	Save(values ...*model.CRMPermission) error
	First() (*model.CRMPermission, error)
	Take() (*model.CRMPermission, error)
	Last() (*model.CRMPermission, error)
	Find() ([]*model.CRMPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMPermission, err error)
	FindInBatches(result *[]*model.CRMPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMPermissionDo
	Assign(attrs ...field.AssignExpr) ICRMPermissionDo
	Joins(fields ...field.RelationField) ICRMPermissionDo
	Preload(fields ...field.RelationField) ICRMPermissionDo
	FirstOrInit() (*model.CRMPermission, error)
	FirstOrCreate() (*model.CRMPermission, error)
	FindByPage(offset int, limit int) (result []*model.CRMPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMPermissionDo) Debug() ICRMPermissionDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMPermissionDo) WithContext(ctx context.Context) ICRMPermissionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMPermissionDo) ReadDB() ICRMPermissionDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMPermissionDo) WriteDB() ICRMPermissionDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMPermissionDo) Session(config *gorm.Session) ICRMPermissionDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMPermissionDo) Clauses(conds ...clause.Expression) ICRMPermissionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMPermissionDo) Returning(value interface{}, columns ...string) ICRMPermissionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMPermissionDo) Not(conds ...gen.Condition) ICRMPermissionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMPermissionDo) Or(conds ...gen.Condition) ICRMPermissionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMPermissionDo) Select(conds ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMPermissionDo) Where(conds ...gen.Condition) ICRMPermissionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMPermissionDo) Order(conds ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMPermissionDo) Distinct(cols ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMPermissionDo) Omit(cols ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMPermissionDo) Join(table schema.Tabler, on ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMPermissionDo) Group(cols ...field.Expr) ICRMPermissionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMPermissionDo) Having(conds ...gen.Condition) ICRMPermissionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMPermissionDo) Limit(limit int) ICRMPermissionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMPermissionDo) Offset(offset int) ICRMPermissionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMPermissionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMPermissionDo) Unscoped() ICRMPermissionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMPermissionDo) Create(values ...*model.CRMPermission) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMPermissionDo) CreateInBatches(values []*model.CRMPermission, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMPermissionDo) Save(values ...*model.CRMPermission) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMPermissionDo) First() (*model.CRMPermission, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMPermission), nil
	}
}

func (c cRMPermissionDo) Take() (*model.CRMPermission, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMPermission), nil
	}
}

func (c cRMPermissionDo) Last() (*model.CRMPermission, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMPermission), nil
	}
}

func (c cRMPermissionDo) Find() ([]*model.CRMPermission, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMPermission), err
}

func (c cRMPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMPermission, err error) {
	buf := make([]*model.CRMPermission, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMPermissionDo) FindInBatches(result *[]*model.CRMPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMPermissionDo) Attrs(attrs ...field.AssignExpr) ICRMPermissionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMPermissionDo) Assign(attrs ...field.AssignExpr) ICRMPermissionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMPermissionDo) Joins(fields ...field.RelationField) ICRMPermissionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMPermissionDo) Preload(fields ...field.RelationField) ICRMPermissionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMPermissionDo) FirstOrInit() (*model.CRMPermission, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMPermission), nil
	}
}

func (c cRMPermissionDo) FirstOrCreate() (*model.CRMPermission, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMPermission), nil
	}
}

func (c cRMPermissionDo) FindByPage(offset int, limit int) (result []*model.CRMPermission, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMPermissionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMPermissionDo) Delete(models ...*model.CRMPermission) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMPermissionDo) withDO(do gen.Dao) *cRMPermissionDo {
	c.DO = *do.(*gen.DO)
	return c
}
