// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMCategory(db *gorm.DB, opts ...gen.DOOption) cRMCategory {
	_cRMCategory := cRMCategory{}

	_cRMCategory.cRMCategoryDo.UseDB(db, opts...)
	_cRMCategory.cRMCategoryDo.UseModel(&model.CRMCategory{})

	tableName := _cRMCategory.cRMCategoryDo.TableName()
	_cRMCategory.ALL = field.NewAsterisk(tableName)
	_cRMCategory.Id = field.NewInt(tableName, "id")
	_cRMCategory.CategoryId = field.NewString(tableName, "category_id")
	_cRMCategory.CategoryName = field.NewString(tableName, "category_name")
	_cRMCategory.CategoryImage = field.NewString(tableName, "category_image")
	_cRMCategory.CategoryType = field.NewInt(tableName, "category_type")
	_cRMCategory.ParentId = field.NewString(tableName, "parent_id")
	_cRMCategory.Status = field.NewString(tableName, "status")
	_cRMCategory.Position = field.NewInt(tableName, "position")
	_cRMCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMCategory.fillFieldMap()

	return _cRMCategory
}

type cRMCategory struct {
	cRMCategoryDo

	ALL           field.Asterisk
	Id            field.Int    // 主键
	CategoryId    field.String // 业务主键
	CategoryName  field.String // 栏目名称
	CategoryImage field.String // 栏目图片
	CategoryType  field.Int    // 栏目类型,1文章,2商品
	ParentId      field.String // 父级id
	Status        field.String // 状态,off禁用,on启用
	Position      field.Int    // 排序
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMCategory) Table(newTableName string) *cRMCategory {
	c.cRMCategoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMCategory) As(alias string) *cRMCategory {
	c.cRMCategoryDo.DO = *(c.cRMCategoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMCategory) updateTableName(table string) *cRMCategory {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.CategoryId = field.NewString(table, "category_id")
	c.CategoryName = field.NewString(table, "category_name")
	c.CategoryImage = field.NewString(table, "category_image")
	c.CategoryType = field.NewInt(table, "category_type")
	c.ParentId = field.NewString(table, "parent_id")
	c.Status = field.NewString(table, "status")
	c.Position = field.NewInt(table, "position")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMCategory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.Id
	c.fieldMap["category_id"] = c.CategoryId
	c.fieldMap["category_name"] = c.CategoryName
	c.fieldMap["category_image"] = c.CategoryImage
	c.fieldMap["category_type"] = c.CategoryType
	c.fieldMap["parent_id"] = c.ParentId
	c.fieldMap["status"] = c.Status
	c.fieldMap["position"] = c.Position
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMCategory) clone(db *gorm.DB) cRMCategory {
	c.cRMCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMCategory) replaceDB(db *gorm.DB) cRMCategory {
	c.cRMCategoryDo.ReplaceDB(db)
	return c
}

type cRMCategoryDo struct{ gen.DO }

type ICRMCategoryDo interface {
	gen.SubQuery
	Debug() ICRMCategoryDo
	WithContext(ctx context.Context) ICRMCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMCategoryDo
	WriteDB() ICRMCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMCategoryDo
	Not(conds ...gen.Condition) ICRMCategoryDo
	Or(conds ...gen.Condition) ICRMCategoryDo
	Select(conds ...field.Expr) ICRMCategoryDo
	Where(conds ...gen.Condition) ICRMCategoryDo
	Order(conds ...field.Expr) ICRMCategoryDo
	Distinct(cols ...field.Expr) ICRMCategoryDo
	Omit(cols ...field.Expr) ICRMCategoryDo
	Join(table schema.Tabler, on ...field.Expr) ICRMCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMCategoryDo
	Group(cols ...field.Expr) ICRMCategoryDo
	Having(conds ...gen.Condition) ICRMCategoryDo
	Limit(limit int) ICRMCategoryDo
	Offset(offset int) ICRMCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMCategoryDo
	Unscoped() ICRMCategoryDo
	Create(values ...*model.CRMCategory) error
	CreateInBatches(values []*model.CRMCategory, batchSize int) error
	Save(values ...*model.CRMCategory) error
	First() (*model.CRMCategory, error)
	Take() (*model.CRMCategory, error)
	Last() (*model.CRMCategory, error)
	Find() ([]*model.CRMCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMCategory, err error)
	FindInBatches(result *[]*model.CRMCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMCategoryDo
	Assign(attrs ...field.AssignExpr) ICRMCategoryDo
	Joins(fields ...field.RelationField) ICRMCategoryDo
	Preload(fields ...field.RelationField) ICRMCategoryDo
	FirstOrInit() (*model.CRMCategory, error)
	FirstOrCreate() (*model.CRMCategory, error)
	FindByPage(offset int, limit int) (result []*model.CRMCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMCategoryDo) Debug() ICRMCategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMCategoryDo) WithContext(ctx context.Context) ICRMCategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMCategoryDo) ReadDB() ICRMCategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMCategoryDo) WriteDB() ICRMCategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMCategoryDo) Session(config *gorm.Session) ICRMCategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMCategoryDo) Clauses(conds ...clause.Expression) ICRMCategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMCategoryDo) Returning(value interface{}, columns ...string) ICRMCategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMCategoryDo) Not(conds ...gen.Condition) ICRMCategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMCategoryDo) Or(conds ...gen.Condition) ICRMCategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMCategoryDo) Select(conds ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMCategoryDo) Where(conds ...gen.Condition) ICRMCategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMCategoryDo) Order(conds ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMCategoryDo) Distinct(cols ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMCategoryDo) Omit(cols ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMCategoryDo) Join(table schema.Tabler, on ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMCategoryDo) Group(cols ...field.Expr) ICRMCategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMCategoryDo) Having(conds ...gen.Condition) ICRMCategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMCategoryDo) Limit(limit int) ICRMCategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMCategoryDo) Offset(offset int) ICRMCategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMCategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMCategoryDo) Unscoped() ICRMCategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMCategoryDo) Create(values ...*model.CRMCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMCategoryDo) CreateInBatches(values []*model.CRMCategory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMCategoryDo) Save(values ...*model.CRMCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMCategoryDo) First() (*model.CRMCategory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMCategory), nil
	}
}

func (c cRMCategoryDo) Take() (*model.CRMCategory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMCategory), nil
	}
}

func (c cRMCategoryDo) Last() (*model.CRMCategory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMCategory), nil
	}
}

func (c cRMCategoryDo) Find() ([]*model.CRMCategory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMCategory), err
}

func (c cRMCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMCategory, err error) {
	buf := make([]*model.CRMCategory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMCategoryDo) FindInBatches(result *[]*model.CRMCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMCategoryDo) Attrs(attrs ...field.AssignExpr) ICRMCategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMCategoryDo) Assign(attrs ...field.AssignExpr) ICRMCategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMCategoryDo) Joins(fields ...field.RelationField) ICRMCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMCategoryDo) Preload(fields ...field.RelationField) ICRMCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMCategoryDo) FirstOrInit() (*model.CRMCategory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMCategory), nil
	}
}

func (c cRMCategoryDo) FirstOrCreate() (*model.CRMCategory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMCategory), nil
	}
}

func (c cRMCategoryDo) FindByPage(offset int, limit int) (result []*model.CRMCategory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMCategoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMCategoryDo) Delete(models ...*model.CRMCategory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMCategoryDo) withDO(do gen.Dao) *cRMCategoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
