// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMArticle(db *gorm.DB, opts ...gen.DOOption) cRMArticle {
	_cRMArticle := cRMArticle{}

	_cRMArticle.cRMArticleDo.UseDB(db, opts...)
	_cRMArticle.cRMArticleDo.UseModel(&model.CRMArticle{})

	tableName := _cRMArticle.cRMArticleDo.TableName()
	_cRMArticle.ALL = field.NewAsterisk(tableName)
	_cRMArticle.Id = field.NewInt(tableName, "id")
	_cRMArticle.ArticleId = field.NewString(tableName, "article_id")
	_cRMArticle.CategoryId = field.NewString(tableName, "category_id")
	_cRMArticle.ArticleName = field.NewString(tableName, "article_name")
	_cRMArticle.ArticleImage = field.NewString(tableName, "article_image")
	_cRMArticle.Status = field.NewString(tableName, "status")
	_cRMArticle.Position = field.NewInt(tableName, "position")
	_cRMArticle.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMArticle.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMArticle.fillFieldMap()

	return _cRMArticle
}

type cRMArticle struct {
	cRMArticleDo

	ALL          field.Asterisk
	Id           field.Int    // 主键
	ArticleId    field.String // 业务主键
	CategoryId   field.String // 栏目Id
	ArticleName  field.String // 文章名称
	ArticleImage field.String // 文章缩略图
	Status       field.String // 状态,off禁用,on启用
	Position     field.Int    // 排序
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMArticle) Table(newTableName string) *cRMArticle {
	c.cRMArticleDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMArticle) As(alias string) *cRMArticle {
	c.cRMArticleDo.DO = *(c.cRMArticleDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMArticle) updateTableName(table string) *cRMArticle {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.ArticleId = field.NewString(table, "article_id")
	c.CategoryId = field.NewString(table, "category_id")
	c.ArticleName = field.NewString(table, "article_name")
	c.ArticleImage = field.NewString(table, "article_image")
	c.Status = field.NewString(table, "status")
	c.Position = field.NewInt(table, "position")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMArticle) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMArticle) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.Id
	c.fieldMap["article_id"] = c.ArticleId
	c.fieldMap["category_id"] = c.CategoryId
	c.fieldMap["article_name"] = c.ArticleName
	c.fieldMap["article_image"] = c.ArticleImage
	c.fieldMap["status"] = c.Status
	c.fieldMap["position"] = c.Position
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMArticle) clone(db *gorm.DB) cRMArticle {
	c.cRMArticleDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMArticle) replaceDB(db *gorm.DB) cRMArticle {
	c.cRMArticleDo.ReplaceDB(db)
	return c
}

type cRMArticleDo struct{ gen.DO }

type ICRMArticleDo interface {
	gen.SubQuery
	Debug() ICRMArticleDo
	WithContext(ctx context.Context) ICRMArticleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMArticleDo
	WriteDB() ICRMArticleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMArticleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMArticleDo
	Not(conds ...gen.Condition) ICRMArticleDo
	Or(conds ...gen.Condition) ICRMArticleDo
	Select(conds ...field.Expr) ICRMArticleDo
	Where(conds ...gen.Condition) ICRMArticleDo
	Order(conds ...field.Expr) ICRMArticleDo
	Distinct(cols ...field.Expr) ICRMArticleDo
	Omit(cols ...field.Expr) ICRMArticleDo
	Join(table schema.Tabler, on ...field.Expr) ICRMArticleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleDo
	Group(cols ...field.Expr) ICRMArticleDo
	Having(conds ...gen.Condition) ICRMArticleDo
	Limit(limit int) ICRMArticleDo
	Offset(offset int) ICRMArticleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleDo
	Unscoped() ICRMArticleDo
	Create(values ...*model.CRMArticle) error
	CreateInBatches(values []*model.CRMArticle, batchSize int) error
	Save(values ...*model.CRMArticle) error
	First() (*model.CRMArticle, error)
	Take() (*model.CRMArticle, error)
	Last() (*model.CRMArticle, error)
	Find() ([]*model.CRMArticle, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticle, err error)
	FindInBatches(result *[]*model.CRMArticle, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMArticle) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMArticleDo
	Assign(attrs ...field.AssignExpr) ICRMArticleDo
	Joins(fields ...field.RelationField) ICRMArticleDo
	Preload(fields ...field.RelationField) ICRMArticleDo
	FirstOrInit() (*model.CRMArticle, error)
	FirstOrCreate() (*model.CRMArticle, error)
	FindByPage(offset int, limit int) (result []*model.CRMArticle, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMArticleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMArticleDo) Debug() ICRMArticleDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMArticleDo) WithContext(ctx context.Context) ICRMArticleDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMArticleDo) ReadDB() ICRMArticleDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMArticleDo) WriteDB() ICRMArticleDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMArticleDo) Session(config *gorm.Session) ICRMArticleDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMArticleDo) Clauses(conds ...clause.Expression) ICRMArticleDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMArticleDo) Returning(value interface{}, columns ...string) ICRMArticleDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMArticleDo) Not(conds ...gen.Condition) ICRMArticleDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMArticleDo) Or(conds ...gen.Condition) ICRMArticleDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMArticleDo) Select(conds ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMArticleDo) Where(conds ...gen.Condition) ICRMArticleDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMArticleDo) Order(conds ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMArticleDo) Distinct(cols ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMArticleDo) Omit(cols ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMArticleDo) Join(table schema.Tabler, on ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMArticleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMArticleDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMArticleDo) Group(cols ...field.Expr) ICRMArticleDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMArticleDo) Having(conds ...gen.Condition) ICRMArticleDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMArticleDo) Limit(limit int) ICRMArticleDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMArticleDo) Offset(offset int) ICRMArticleDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMArticleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMArticleDo) Unscoped() ICRMArticleDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMArticleDo) Create(values ...*model.CRMArticle) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMArticleDo) CreateInBatches(values []*model.CRMArticle, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMArticleDo) Save(values ...*model.CRMArticle) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMArticleDo) First() (*model.CRMArticle, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticle), nil
	}
}

func (c cRMArticleDo) Take() (*model.CRMArticle, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticle), nil
	}
}

func (c cRMArticleDo) Last() (*model.CRMArticle, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticle), nil
	}
}

func (c cRMArticleDo) Find() ([]*model.CRMArticle, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMArticle), err
}

func (c cRMArticleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticle, err error) {
	buf := make([]*model.CRMArticle, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMArticleDo) FindInBatches(result *[]*model.CRMArticle, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMArticleDo) Attrs(attrs ...field.AssignExpr) ICRMArticleDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMArticleDo) Assign(attrs ...field.AssignExpr) ICRMArticleDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMArticleDo) Joins(fields ...field.RelationField) ICRMArticleDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMArticleDo) Preload(fields ...field.RelationField) ICRMArticleDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMArticleDo) FirstOrInit() (*model.CRMArticle, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticle), nil
	}
}

func (c cRMArticleDo) FirstOrCreate() (*model.CRMArticle, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticle), nil
	}
}

func (c cRMArticleDo) FindByPage(offset int, limit int) (result []*model.CRMArticle, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMArticleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMArticleDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMArticleDo) Delete(models ...*model.CRMArticle) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMArticleDo) withDO(do gen.Dao) *cRMArticleDo {
	c.DO = *do.(*gen.DO)
	return c
}
