// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMAdmin(db *gorm.DB, opts ...gen.DOOption) cRMAdmin {
	_cRMAdmin := cRMAdmin{}

	_cRMAdmin.cRMAdminDo.UseDB(db, opts...)
	_cRMAdmin.cRMAdminDo.UseModel(&model.CRMAdmin{})

	tableName := _cRMAdmin.cRMAdminDo.TableName()
	_cRMAdmin.ALL = field.NewAsterisk(tableName)
	_cRMAdmin.Id = field.NewInt(tableName, "id")
	_cRMAdmin.UserName = field.NewString(tableName, "user_name")
	_cRMAdmin.UserPhone = field.NewString(tableName, "user_phone")
	_cRMAdmin.Password = field.NewString(tableName, "password")
	_cRMAdmin.DepartmentId = field.NewInt(tableName, "department_id")
	_cRMAdmin.Status = field.NewInt(tableName, "status")
	_cRMAdmin.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMAdmin.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMAdmin.fillFieldMap()

	return _cRMAdmin
}

type cRMAdmin struct {
	cRMAdminDo

	ALL          field.Asterisk
	Id           field.Int    // 主键
	UserName     field.String // 用户名
	UserPhone    field.String // 手机号
	Password     field.String // 密码
	DepartmentId field.Int    // 所属部门ID
	Status       field.Int    // 状态,0禁用,1启用
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMAdmin) Table(newTableName string) *cRMAdmin {
	c.cRMAdminDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMAdmin) As(alias string) *cRMAdmin {
	c.cRMAdminDo.DO = *(c.cRMAdminDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMAdmin) updateTableName(table string) *cRMAdmin {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.UserName = field.NewString(table, "user_name")
	c.UserPhone = field.NewString(table, "user_phone")
	c.Password = field.NewString(table, "password")
	c.DepartmentId = field.NewInt(table, "department_id")
	c.Status = field.NewInt(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMAdmin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMAdmin) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.Id
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["user_phone"] = c.UserPhone
	c.fieldMap["password"] = c.Password
	c.fieldMap["department_id"] = c.DepartmentId
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMAdmin) clone(db *gorm.DB) cRMAdmin {
	c.cRMAdminDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMAdmin) replaceDB(db *gorm.DB) cRMAdmin {
	c.cRMAdminDo.ReplaceDB(db)
	return c
}

type cRMAdminDo struct{ gen.DO }

type ICRMAdminDo interface {
	gen.SubQuery
	Debug() ICRMAdminDo
	WithContext(ctx context.Context) ICRMAdminDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMAdminDo
	WriteDB() ICRMAdminDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMAdminDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMAdminDo
	Not(conds ...gen.Condition) ICRMAdminDo
	Or(conds ...gen.Condition) ICRMAdminDo
	Select(conds ...field.Expr) ICRMAdminDo
	Where(conds ...gen.Condition) ICRMAdminDo
	Order(conds ...field.Expr) ICRMAdminDo
	Distinct(cols ...field.Expr) ICRMAdminDo
	Omit(cols ...field.Expr) ICRMAdminDo
	Join(table schema.Tabler, on ...field.Expr) ICRMAdminDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMAdminDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMAdminDo
	Group(cols ...field.Expr) ICRMAdminDo
	Having(conds ...gen.Condition) ICRMAdminDo
	Limit(limit int) ICRMAdminDo
	Offset(offset int) ICRMAdminDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMAdminDo
	Unscoped() ICRMAdminDo
	Create(values ...*model.CRMAdmin) error
	CreateInBatches(values []*model.CRMAdmin, batchSize int) error
	Save(values ...*model.CRMAdmin) error
	First() (*model.CRMAdmin, error)
	Take() (*model.CRMAdmin, error)
	Last() (*model.CRMAdmin, error)
	Find() ([]*model.CRMAdmin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMAdmin, err error)
	FindInBatches(result *[]*model.CRMAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMAdmin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMAdminDo
	Assign(attrs ...field.AssignExpr) ICRMAdminDo
	Joins(fields ...field.RelationField) ICRMAdminDo
	Preload(fields ...field.RelationField) ICRMAdminDo
	FirstOrInit() (*model.CRMAdmin, error)
	FirstOrCreate() (*model.CRMAdmin, error)
	FindByPage(offset int, limit int) (result []*model.CRMAdmin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMAdminDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMAdminDo) Debug() ICRMAdminDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMAdminDo) WithContext(ctx context.Context) ICRMAdminDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMAdminDo) ReadDB() ICRMAdminDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMAdminDo) WriteDB() ICRMAdminDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMAdminDo) Session(config *gorm.Session) ICRMAdminDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMAdminDo) Clauses(conds ...clause.Expression) ICRMAdminDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMAdminDo) Returning(value interface{}, columns ...string) ICRMAdminDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMAdminDo) Not(conds ...gen.Condition) ICRMAdminDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMAdminDo) Or(conds ...gen.Condition) ICRMAdminDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMAdminDo) Select(conds ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMAdminDo) Where(conds ...gen.Condition) ICRMAdminDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMAdminDo) Order(conds ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMAdminDo) Distinct(cols ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMAdminDo) Omit(cols ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMAdminDo) Join(table schema.Tabler, on ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMAdminDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMAdminDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMAdminDo) Group(cols ...field.Expr) ICRMAdminDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMAdminDo) Having(conds ...gen.Condition) ICRMAdminDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMAdminDo) Limit(limit int) ICRMAdminDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMAdminDo) Offset(offset int) ICRMAdminDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMAdminDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMAdminDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMAdminDo) Unscoped() ICRMAdminDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMAdminDo) Create(values ...*model.CRMAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMAdminDo) CreateInBatches(values []*model.CRMAdmin, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMAdminDo) Save(values ...*model.CRMAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMAdminDo) First() (*model.CRMAdmin, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMAdmin), nil
	}
}

func (c cRMAdminDo) Take() (*model.CRMAdmin, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMAdmin), nil
	}
}

func (c cRMAdminDo) Last() (*model.CRMAdmin, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMAdmin), nil
	}
}

func (c cRMAdminDo) Find() ([]*model.CRMAdmin, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMAdmin), err
}

func (c cRMAdminDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMAdmin, err error) {
	buf := make([]*model.CRMAdmin, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMAdminDo) FindInBatches(result *[]*model.CRMAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMAdminDo) Attrs(attrs ...field.AssignExpr) ICRMAdminDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMAdminDo) Assign(attrs ...field.AssignExpr) ICRMAdminDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMAdminDo) Joins(fields ...field.RelationField) ICRMAdminDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMAdminDo) Preload(fields ...field.RelationField) ICRMAdminDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMAdminDo) FirstOrInit() (*model.CRMAdmin, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMAdmin), nil
	}
}

func (c cRMAdminDo) FirstOrCreate() (*model.CRMAdmin, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMAdmin), nil
	}
}

func (c cRMAdminDo) FindByPage(offset int, limit int) (result []*model.CRMAdmin, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMAdminDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMAdminDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMAdminDo) Delete(models ...*model.CRMAdmin) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMAdminDo) withDO(do gen.Dao) *cRMAdminDo {
	c.DO = *do.(*gen.DO)
	return c
}
