// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMRole(db *gorm.DB, opts ...gen.DOOption) cRMRole {
	_cRMRole := cRMRole{}

	_cRMRole.cRMRoleDo.UseDB(db, opts...)
	_cRMRole.cRMRoleDo.UseModel(&model.CRMRole{})

	tableName := _cRMRole.cRMRoleDo.TableName()
	_cRMRole.ALL = field.NewAsterisk(tableName)
	_cRMRole.Id = field.NewInt(tableName, "id")
	_cRMRole.RoleId = field.NewString(tableName, "role_id")
	_cRMRole.RoleName = field.NewString(tableName, "role_name")
	_cRMRole.Status = field.NewString(tableName, "status")
	_cRMRole.IsInit = field.NewString(tableName, "is_init")
	_cRMRole.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMRole.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMRole.fillFieldMap()

	return _cRMRole
}

type cRMRole struct {
	cRMRoleDo

	ALL       field.Asterisk
	Id        field.Int    // 主键
	RoleId    field.String // 业务主键
	RoleName  field.String // 角色名称
	Status    field.String // 状态,off禁用,on启用
	IsInit    field.String // 是否初始数据,off否,on是
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMRole) Table(newTableName string) *cRMRole {
	c.cRMRoleDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMRole) As(alias string) *cRMRole {
	c.cRMRoleDo.DO = *(c.cRMRoleDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMRole) updateTableName(table string) *cRMRole {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.RoleId = field.NewString(table, "role_id")
	c.RoleName = field.NewString(table, "role_name")
	c.Status = field.NewString(table, "status")
	c.IsInit = field.NewString(table, "is_init")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMRole) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.Id
	c.fieldMap["role_id"] = c.RoleId
	c.fieldMap["role_name"] = c.RoleName
	c.fieldMap["status"] = c.Status
	c.fieldMap["is_init"] = c.IsInit
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMRole) clone(db *gorm.DB) cRMRole {
	c.cRMRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMRole) replaceDB(db *gorm.DB) cRMRole {
	c.cRMRoleDo.ReplaceDB(db)
	return c
}

type cRMRoleDo struct{ gen.DO }

type ICRMRoleDo interface {
	gen.SubQuery
	Debug() ICRMRoleDo
	WithContext(ctx context.Context) ICRMRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMRoleDo
	WriteDB() ICRMRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMRoleDo
	Not(conds ...gen.Condition) ICRMRoleDo
	Or(conds ...gen.Condition) ICRMRoleDo
	Select(conds ...field.Expr) ICRMRoleDo
	Where(conds ...gen.Condition) ICRMRoleDo
	Order(conds ...field.Expr) ICRMRoleDo
	Distinct(cols ...field.Expr) ICRMRoleDo
	Omit(cols ...field.Expr) ICRMRoleDo
	Join(table schema.Tabler, on ...field.Expr) ICRMRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMRoleDo
	Group(cols ...field.Expr) ICRMRoleDo
	Having(conds ...gen.Condition) ICRMRoleDo
	Limit(limit int) ICRMRoleDo
	Offset(offset int) ICRMRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMRoleDo
	Unscoped() ICRMRoleDo
	Create(values ...*model.CRMRole) error
	CreateInBatches(values []*model.CRMRole, batchSize int) error
	Save(values ...*model.CRMRole) error
	First() (*model.CRMRole, error)
	Take() (*model.CRMRole, error)
	Last() (*model.CRMRole, error)
	Find() ([]*model.CRMRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMRole, err error)
	FindInBatches(result *[]*model.CRMRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMRoleDo
	Assign(attrs ...field.AssignExpr) ICRMRoleDo
	Joins(fields ...field.RelationField) ICRMRoleDo
	Preload(fields ...field.RelationField) ICRMRoleDo
	FirstOrInit() (*model.CRMRole, error)
	FirstOrCreate() (*model.CRMRole, error)
	FindByPage(offset int, limit int) (result []*model.CRMRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMRoleDo) Debug() ICRMRoleDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMRoleDo) WithContext(ctx context.Context) ICRMRoleDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMRoleDo) ReadDB() ICRMRoleDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMRoleDo) WriteDB() ICRMRoleDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMRoleDo) Session(config *gorm.Session) ICRMRoleDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMRoleDo) Clauses(conds ...clause.Expression) ICRMRoleDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMRoleDo) Returning(value interface{}, columns ...string) ICRMRoleDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMRoleDo) Not(conds ...gen.Condition) ICRMRoleDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMRoleDo) Or(conds ...gen.Condition) ICRMRoleDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMRoleDo) Select(conds ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMRoleDo) Where(conds ...gen.Condition) ICRMRoleDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMRoleDo) Order(conds ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMRoleDo) Distinct(cols ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMRoleDo) Omit(cols ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMRoleDo) Join(table schema.Tabler, on ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMRoleDo) Group(cols ...field.Expr) ICRMRoleDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMRoleDo) Having(conds ...gen.Condition) ICRMRoleDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMRoleDo) Limit(limit int) ICRMRoleDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMRoleDo) Offset(offset int) ICRMRoleDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMRoleDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMRoleDo) Unscoped() ICRMRoleDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMRoleDo) Create(values ...*model.CRMRole) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMRoleDo) CreateInBatches(values []*model.CRMRole, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMRoleDo) Save(values ...*model.CRMRole) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMRoleDo) First() (*model.CRMRole, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRole), nil
	}
}

func (c cRMRoleDo) Take() (*model.CRMRole, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRole), nil
	}
}

func (c cRMRoleDo) Last() (*model.CRMRole, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRole), nil
	}
}

func (c cRMRoleDo) Find() ([]*model.CRMRole, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMRole), err
}

func (c cRMRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMRole, err error) {
	buf := make([]*model.CRMRole, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMRoleDo) FindInBatches(result *[]*model.CRMRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMRoleDo) Attrs(attrs ...field.AssignExpr) ICRMRoleDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMRoleDo) Assign(attrs ...field.AssignExpr) ICRMRoleDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMRoleDo) Joins(fields ...field.RelationField) ICRMRoleDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMRoleDo) Preload(fields ...field.RelationField) ICRMRoleDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMRoleDo) FirstOrInit() (*model.CRMRole, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRole), nil
	}
}

func (c cRMRoleDo) FirstOrCreate() (*model.CRMRole, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRole), nil
	}
}

func (c cRMRoleDo) FindByPage(offset int, limit int) (result []*model.CRMRole, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMRoleDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMRoleDo) Delete(models ...*model.CRMRole) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMRoleDo) withDO(do gen.Dao) *cRMRoleDo {
	c.DO = *do.(*gen.DO)
	return c
}
