// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMRolePermission(db *gorm.DB, opts ...gen.DOOption) cRMRolePermission {
	_cRMRolePermission := cRMRolePermission{}

	_cRMRolePermission.cRMRolePermissionDo.UseDB(db, opts...)
	_cRMRolePermission.cRMRolePermissionDo.UseModel(&model.CRMRolePermission{})

	tableName := _cRMRolePermission.cRMRolePermissionDo.TableName()
	_cRMRolePermission.ALL = field.NewAsterisk(tableName)
	_cRMRolePermission.Id = field.NewInt(tableName, "id")
	_cRMRolePermission.RoleId = field.NewString(tableName, "role_id")
	_cRMRolePermission.PermissionId = field.NewString(tableName, "permission_id")
	_cRMRolePermission.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMRolePermission.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMRolePermission.fillFieldMap()

	return _cRMRolePermission
}

type cRMRolePermission struct {
	cRMRolePermissionDo

	ALL          field.Asterisk
	Id           field.Int    // 自增主键
	RoleId       field.String // 角色ID
	PermissionId field.String // 权限ID
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMRolePermission) Table(newTableName string) *cRMRolePermission {
	c.cRMRolePermissionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMRolePermission) As(alias string) *cRMRolePermission {
	c.cRMRolePermissionDo.DO = *(c.cRMRolePermissionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMRolePermission) updateTableName(table string) *cRMRolePermission {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.RoleId = field.NewString(table, "role_id")
	c.PermissionId = field.NewString(table, "permission_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMRolePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMRolePermission) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.Id
	c.fieldMap["role_id"] = c.RoleId
	c.fieldMap["permission_id"] = c.PermissionId
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMRolePermission) clone(db *gorm.DB) cRMRolePermission {
	c.cRMRolePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMRolePermission) replaceDB(db *gorm.DB) cRMRolePermission {
	c.cRMRolePermissionDo.ReplaceDB(db)
	return c
}

type cRMRolePermissionDo struct{ gen.DO }

type ICRMRolePermissionDo interface {
	gen.SubQuery
	Debug() ICRMRolePermissionDo
	WithContext(ctx context.Context) ICRMRolePermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMRolePermissionDo
	WriteDB() ICRMRolePermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMRolePermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMRolePermissionDo
	Not(conds ...gen.Condition) ICRMRolePermissionDo
	Or(conds ...gen.Condition) ICRMRolePermissionDo
	Select(conds ...field.Expr) ICRMRolePermissionDo
	Where(conds ...gen.Condition) ICRMRolePermissionDo
	Order(conds ...field.Expr) ICRMRolePermissionDo
	Distinct(cols ...field.Expr) ICRMRolePermissionDo
	Omit(cols ...field.Expr) ICRMRolePermissionDo
	Join(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo
	Group(cols ...field.Expr) ICRMRolePermissionDo
	Having(conds ...gen.Condition) ICRMRolePermissionDo
	Limit(limit int) ICRMRolePermissionDo
	Offset(offset int) ICRMRolePermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMRolePermissionDo
	Unscoped() ICRMRolePermissionDo
	Create(values ...*model.CRMRolePermission) error
	CreateInBatches(values []*model.CRMRolePermission, batchSize int) error
	Save(values ...*model.CRMRolePermission) error
	First() (*model.CRMRolePermission, error)
	Take() (*model.CRMRolePermission, error)
	Last() (*model.CRMRolePermission, error)
	Find() ([]*model.CRMRolePermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMRolePermission, err error)
	FindInBatches(result *[]*model.CRMRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMRolePermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMRolePermissionDo
	Assign(attrs ...field.AssignExpr) ICRMRolePermissionDo
	Joins(fields ...field.RelationField) ICRMRolePermissionDo
	Preload(fields ...field.RelationField) ICRMRolePermissionDo
	FirstOrInit() (*model.CRMRolePermission, error)
	FirstOrCreate() (*model.CRMRolePermission, error)
	FindByPage(offset int, limit int) (result []*model.CRMRolePermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMRolePermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMRolePermissionDo) Debug() ICRMRolePermissionDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMRolePermissionDo) WithContext(ctx context.Context) ICRMRolePermissionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMRolePermissionDo) ReadDB() ICRMRolePermissionDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMRolePermissionDo) WriteDB() ICRMRolePermissionDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMRolePermissionDo) Session(config *gorm.Session) ICRMRolePermissionDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMRolePermissionDo) Clauses(conds ...clause.Expression) ICRMRolePermissionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMRolePermissionDo) Returning(value interface{}, columns ...string) ICRMRolePermissionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMRolePermissionDo) Not(conds ...gen.Condition) ICRMRolePermissionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMRolePermissionDo) Or(conds ...gen.Condition) ICRMRolePermissionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMRolePermissionDo) Select(conds ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMRolePermissionDo) Where(conds ...gen.Condition) ICRMRolePermissionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMRolePermissionDo) Order(conds ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMRolePermissionDo) Distinct(cols ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMRolePermissionDo) Omit(cols ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMRolePermissionDo) Join(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMRolePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMRolePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMRolePermissionDo) Group(cols ...field.Expr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMRolePermissionDo) Having(conds ...gen.Condition) ICRMRolePermissionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMRolePermissionDo) Limit(limit int) ICRMRolePermissionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMRolePermissionDo) Offset(offset int) ICRMRolePermissionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMRolePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMRolePermissionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMRolePermissionDo) Unscoped() ICRMRolePermissionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMRolePermissionDo) Create(values ...*model.CRMRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMRolePermissionDo) CreateInBatches(values []*model.CRMRolePermission, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMRolePermissionDo) Save(values ...*model.CRMRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMRolePermissionDo) First() (*model.CRMRolePermission, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRolePermission), nil
	}
}

func (c cRMRolePermissionDo) Take() (*model.CRMRolePermission, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRolePermission), nil
	}
}

func (c cRMRolePermissionDo) Last() (*model.CRMRolePermission, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRolePermission), nil
	}
}

func (c cRMRolePermissionDo) Find() ([]*model.CRMRolePermission, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMRolePermission), err
}

func (c cRMRolePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMRolePermission, err error) {
	buf := make([]*model.CRMRolePermission, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMRolePermissionDo) FindInBatches(result *[]*model.CRMRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMRolePermissionDo) Attrs(attrs ...field.AssignExpr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMRolePermissionDo) Assign(attrs ...field.AssignExpr) ICRMRolePermissionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMRolePermissionDo) Joins(fields ...field.RelationField) ICRMRolePermissionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMRolePermissionDo) Preload(fields ...field.RelationField) ICRMRolePermissionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMRolePermissionDo) FirstOrInit() (*model.CRMRolePermission, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRolePermission), nil
	}
}

func (c cRMRolePermissionDo) FirstOrCreate() (*model.CRMRolePermission, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMRolePermission), nil
	}
}

func (c cRMRolePermissionDo) FindByPage(offset int, limit int) (result []*model.CRMRolePermission, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMRolePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMRolePermissionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMRolePermissionDo) Delete(models ...*model.CRMRolePermission) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMRolePermissionDo) withDO(do gen.Dao) *cRMRolePermissionDo {
	c.DO = *do.(*gen.DO)
	return c
}
