// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMArticleContent(db *gorm.DB, opts ...gen.DOOption) cRMArticleContent {
	_cRMArticleContent := cRMArticleContent{}

	_cRMArticleContent.cRMArticleContentDo.UseDB(db, opts...)
	_cRMArticleContent.cRMArticleContentDo.UseModel(&model.CRMArticleContent{})

	tableName := _cRMArticleContent.cRMArticleContentDo.TableName()
	_cRMArticleContent.ALL = field.NewAsterisk(tableName)
	_cRMArticleContent.Id = field.NewInt(tableName, "id")
	_cRMArticleContent.ContentId = field.NewString(tableName, "content_id")
	_cRMArticleContent.ArticleId = field.NewString(tableName, "article_id")
	_cRMArticleContent.ArticleContent = field.NewString(tableName, "article_content")
	_cRMArticleContent.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMArticleContent.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMArticleContent.fillFieldMap()

	return _cRMArticleContent
}

type cRMArticleContent struct {
	cRMArticleContentDo

	ALL            field.Asterisk
	Id             field.Int    // 主键
	ContentId      field.String // 业务主键
	ArticleId      field.String // 文章Id
	ArticleContent field.String // 文章内容
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMArticleContent) Table(newTableName string) *cRMArticleContent {
	c.cRMArticleContentDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMArticleContent) As(alias string) *cRMArticleContent {
	c.cRMArticleContentDo.DO = *(c.cRMArticleContentDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMArticleContent) updateTableName(table string) *cRMArticleContent {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.ContentId = field.NewString(table, "content_id")
	c.ArticleId = field.NewString(table, "article_id")
	c.ArticleContent = field.NewString(table, "article_content")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMArticleContent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMArticleContent) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.Id
	c.fieldMap["content_id"] = c.ContentId
	c.fieldMap["article_id"] = c.ArticleId
	c.fieldMap["article_content"] = c.ArticleContent
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMArticleContent) clone(db *gorm.DB) cRMArticleContent {
	c.cRMArticleContentDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMArticleContent) replaceDB(db *gorm.DB) cRMArticleContent {
	c.cRMArticleContentDo.ReplaceDB(db)
	return c
}

type cRMArticleContentDo struct{ gen.DO }

type ICRMArticleContentDo interface {
	gen.SubQuery
	Debug() ICRMArticleContentDo
	WithContext(ctx context.Context) ICRMArticleContentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMArticleContentDo
	WriteDB() ICRMArticleContentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMArticleContentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMArticleContentDo
	Not(conds ...gen.Condition) ICRMArticleContentDo
	Or(conds ...gen.Condition) ICRMArticleContentDo
	Select(conds ...field.Expr) ICRMArticleContentDo
	Where(conds ...gen.Condition) ICRMArticleContentDo
	Order(conds ...field.Expr) ICRMArticleContentDo
	Distinct(cols ...field.Expr) ICRMArticleContentDo
	Omit(cols ...field.Expr) ICRMArticleContentDo
	Join(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo
	Group(cols ...field.Expr) ICRMArticleContentDo
	Having(conds ...gen.Condition) ICRMArticleContentDo
	Limit(limit int) ICRMArticleContentDo
	Offset(offset int) ICRMArticleContentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleContentDo
	Unscoped() ICRMArticleContentDo
	Create(values ...*model.CRMArticleContent) error
	CreateInBatches(values []*model.CRMArticleContent, batchSize int) error
	Save(values ...*model.CRMArticleContent) error
	First() (*model.CRMArticleContent, error)
	Take() (*model.CRMArticleContent, error)
	Last() (*model.CRMArticleContent, error)
	Find() ([]*model.CRMArticleContent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticleContent, err error)
	FindInBatches(result *[]*model.CRMArticleContent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMArticleContent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMArticleContentDo
	Assign(attrs ...field.AssignExpr) ICRMArticleContentDo
	Joins(fields ...field.RelationField) ICRMArticleContentDo
	Preload(fields ...field.RelationField) ICRMArticleContentDo
	FirstOrInit() (*model.CRMArticleContent, error)
	FirstOrCreate() (*model.CRMArticleContent, error)
	FindByPage(offset int, limit int) (result []*model.CRMArticleContent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMArticleContentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMArticleContentDo) Debug() ICRMArticleContentDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMArticleContentDo) WithContext(ctx context.Context) ICRMArticleContentDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMArticleContentDo) ReadDB() ICRMArticleContentDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMArticleContentDo) WriteDB() ICRMArticleContentDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMArticleContentDo) Session(config *gorm.Session) ICRMArticleContentDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMArticleContentDo) Clauses(conds ...clause.Expression) ICRMArticleContentDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMArticleContentDo) Returning(value interface{}, columns ...string) ICRMArticleContentDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMArticleContentDo) Not(conds ...gen.Condition) ICRMArticleContentDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMArticleContentDo) Or(conds ...gen.Condition) ICRMArticleContentDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMArticleContentDo) Select(conds ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMArticleContentDo) Where(conds ...gen.Condition) ICRMArticleContentDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMArticleContentDo) Order(conds ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMArticleContentDo) Distinct(cols ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMArticleContentDo) Omit(cols ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMArticleContentDo) Join(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMArticleContentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMArticleContentDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMArticleContentDo) Group(cols ...field.Expr) ICRMArticleContentDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMArticleContentDo) Having(conds ...gen.Condition) ICRMArticleContentDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMArticleContentDo) Limit(limit int) ICRMArticleContentDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMArticleContentDo) Offset(offset int) ICRMArticleContentDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMArticleContentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleContentDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMArticleContentDo) Unscoped() ICRMArticleContentDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMArticleContentDo) Create(values ...*model.CRMArticleContent) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMArticleContentDo) CreateInBatches(values []*model.CRMArticleContent, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMArticleContentDo) Save(values ...*model.CRMArticleContent) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMArticleContentDo) First() (*model.CRMArticleContent, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleContent), nil
	}
}

func (c cRMArticleContentDo) Take() (*model.CRMArticleContent, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleContent), nil
	}
}

func (c cRMArticleContentDo) Last() (*model.CRMArticleContent, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleContent), nil
	}
}

func (c cRMArticleContentDo) Find() ([]*model.CRMArticleContent, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMArticleContent), err
}

func (c cRMArticleContentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticleContent, err error) {
	buf := make([]*model.CRMArticleContent, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMArticleContentDo) FindInBatches(result *[]*model.CRMArticleContent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMArticleContentDo) Attrs(attrs ...field.AssignExpr) ICRMArticleContentDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMArticleContentDo) Assign(attrs ...field.AssignExpr) ICRMArticleContentDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMArticleContentDo) Joins(fields ...field.RelationField) ICRMArticleContentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMArticleContentDo) Preload(fields ...field.RelationField) ICRMArticleContentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMArticleContentDo) FirstOrInit() (*model.CRMArticleContent, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleContent), nil
	}
}

func (c cRMArticleContentDo) FirstOrCreate() (*model.CRMArticleContent, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleContent), nil
	}
}

func (c cRMArticleContentDo) FindByPage(offset int, limit int) (result []*model.CRMArticleContent, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMArticleContentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMArticleContentDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMArticleContentDo) Delete(models ...*model.CRMArticleContent) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMArticleContentDo) withDO(do gen.Dao) *cRMArticleContentDo {
	c.DO = *do.(*gen.DO)
	return c
}
