// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newCRMArticleCategory(db *gorm.DB, opts ...gen.DOOption) cRMArticleCategory {
	_cRMArticleCategory := cRMArticleCategory{}

	_cRMArticleCategory.cRMArticleCategoryDo.UseDB(db, opts...)
	_cRMArticleCategory.cRMArticleCategoryDo.UseModel(&model.CRMArticleCategory{})

	tableName := _cRMArticleCategory.cRMArticleCategoryDo.TableName()
	_cRMArticleCategory.ALL = field.NewAsterisk(tableName)
	_cRMArticleCategory.Id = field.NewInt(tableName, "id")
	_cRMArticleCategory.CategoryId = field.NewString(tableName, "category_id")
	_cRMArticleCategory.CategoryName = field.NewString(tableName, "category_name")
	_cRMArticleCategory.CategoryImage = field.NewString(tableName, "category_image")
	_cRMArticleCategory.ParentId = field.NewString(tableName, "parent_id")
	_cRMArticleCategory.Status = field.NewString(tableName, "status")
	_cRMArticleCategory.Position = field.NewInt(tableName, "position")
	_cRMArticleCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_cRMArticleCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cRMArticleCategory.fillFieldMap()

	return _cRMArticleCategory
}

type cRMArticleCategory struct {
	cRMArticleCategoryDo

	ALL           field.Asterisk
	Id            field.Int    // 主键
	CategoryId    field.String // 业务主键
	CategoryName  field.String // 栏目名称
	CategoryImage field.String // 栏目图片
	ParentId      field.String // 父级id
	Status        field.String // 状态,off禁用,on启用
	Position      field.Int    // 排序
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c cRMArticleCategory) Table(newTableName string) *cRMArticleCategory {
	c.cRMArticleCategoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cRMArticleCategory) As(alias string) *cRMArticleCategory {
	c.cRMArticleCategoryDo.DO = *(c.cRMArticleCategoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cRMArticleCategory) updateTableName(table string) *cRMArticleCategory {
	c.ALL = field.NewAsterisk(table)
	c.Id = field.NewInt(table, "id")
	c.CategoryId = field.NewString(table, "category_id")
	c.CategoryName = field.NewString(table, "category_name")
	c.CategoryImage = field.NewString(table, "category_image")
	c.ParentId = field.NewString(table, "parent_id")
	c.Status = field.NewString(table, "status")
	c.Position = field.NewInt(table, "position")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cRMArticleCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cRMArticleCategory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.Id
	c.fieldMap["category_id"] = c.CategoryId
	c.fieldMap["category_name"] = c.CategoryName
	c.fieldMap["category_image"] = c.CategoryImage
	c.fieldMap["parent_id"] = c.ParentId
	c.fieldMap["status"] = c.Status
	c.fieldMap["position"] = c.Position
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cRMArticleCategory) clone(db *gorm.DB) cRMArticleCategory {
	c.cRMArticleCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cRMArticleCategory) replaceDB(db *gorm.DB) cRMArticleCategory {
	c.cRMArticleCategoryDo.ReplaceDB(db)
	return c
}

type cRMArticleCategoryDo struct{ gen.DO }

type ICRMArticleCategoryDo interface {
	gen.SubQuery
	Debug() ICRMArticleCategoryDo
	WithContext(ctx context.Context) ICRMArticleCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICRMArticleCategoryDo
	WriteDB() ICRMArticleCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICRMArticleCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICRMArticleCategoryDo
	Not(conds ...gen.Condition) ICRMArticleCategoryDo
	Or(conds ...gen.Condition) ICRMArticleCategoryDo
	Select(conds ...field.Expr) ICRMArticleCategoryDo
	Where(conds ...gen.Condition) ICRMArticleCategoryDo
	Order(conds ...field.Expr) ICRMArticleCategoryDo
	Distinct(cols ...field.Expr) ICRMArticleCategoryDo
	Omit(cols ...field.Expr) ICRMArticleCategoryDo
	Join(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo
	Group(cols ...field.Expr) ICRMArticleCategoryDo
	Having(conds ...gen.Condition) ICRMArticleCategoryDo
	Limit(limit int) ICRMArticleCategoryDo
	Offset(offset int) ICRMArticleCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleCategoryDo
	Unscoped() ICRMArticleCategoryDo
	Create(values ...*model.CRMArticleCategory) error
	CreateInBatches(values []*model.CRMArticleCategory, batchSize int) error
	Save(values ...*model.CRMArticleCategory) error
	First() (*model.CRMArticleCategory, error)
	Take() (*model.CRMArticleCategory, error)
	Last() (*model.CRMArticleCategory, error)
	Find() ([]*model.CRMArticleCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticleCategory, err error)
	FindInBatches(result *[]*model.CRMArticleCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CRMArticleCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICRMArticleCategoryDo
	Assign(attrs ...field.AssignExpr) ICRMArticleCategoryDo
	Joins(fields ...field.RelationField) ICRMArticleCategoryDo
	Preload(fields ...field.RelationField) ICRMArticleCategoryDo
	FirstOrInit() (*model.CRMArticleCategory, error)
	FirstOrCreate() (*model.CRMArticleCategory, error)
	FindByPage(offset int, limit int) (result []*model.CRMArticleCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICRMArticleCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cRMArticleCategoryDo) Debug() ICRMArticleCategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c cRMArticleCategoryDo) WithContext(ctx context.Context) ICRMArticleCategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cRMArticleCategoryDo) ReadDB() ICRMArticleCategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c cRMArticleCategoryDo) WriteDB() ICRMArticleCategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c cRMArticleCategoryDo) Session(config *gorm.Session) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c cRMArticleCategoryDo) Clauses(conds ...clause.Expression) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cRMArticleCategoryDo) Returning(value interface{}, columns ...string) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cRMArticleCategoryDo) Not(conds ...gen.Condition) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cRMArticleCategoryDo) Or(conds ...gen.Condition) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cRMArticleCategoryDo) Select(conds ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cRMArticleCategoryDo) Where(conds ...gen.Condition) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cRMArticleCategoryDo) Order(conds ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cRMArticleCategoryDo) Distinct(cols ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cRMArticleCategoryDo) Omit(cols ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cRMArticleCategoryDo) Join(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cRMArticleCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cRMArticleCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cRMArticleCategoryDo) Group(cols ...field.Expr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cRMArticleCategoryDo) Having(conds ...gen.Condition) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cRMArticleCategoryDo) Limit(limit int) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cRMArticleCategoryDo) Offset(offset int) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cRMArticleCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cRMArticleCategoryDo) Unscoped() ICRMArticleCategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cRMArticleCategoryDo) Create(values ...*model.CRMArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cRMArticleCategoryDo) CreateInBatches(values []*model.CRMArticleCategory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cRMArticleCategoryDo) Save(values ...*model.CRMArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cRMArticleCategoryDo) First() (*model.CRMArticleCategory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleCategory), nil
	}
}

func (c cRMArticleCategoryDo) Take() (*model.CRMArticleCategory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleCategory), nil
	}
}

func (c cRMArticleCategoryDo) Last() (*model.CRMArticleCategory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleCategory), nil
	}
}

func (c cRMArticleCategoryDo) Find() ([]*model.CRMArticleCategory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CRMArticleCategory), err
}

func (c cRMArticleCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CRMArticleCategory, err error) {
	buf := make([]*model.CRMArticleCategory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cRMArticleCategoryDo) FindInBatches(result *[]*model.CRMArticleCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cRMArticleCategoryDo) Attrs(attrs ...field.AssignExpr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cRMArticleCategoryDo) Assign(attrs ...field.AssignExpr) ICRMArticleCategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cRMArticleCategoryDo) Joins(fields ...field.RelationField) ICRMArticleCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cRMArticleCategoryDo) Preload(fields ...field.RelationField) ICRMArticleCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cRMArticleCategoryDo) FirstOrInit() (*model.CRMArticleCategory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleCategory), nil
	}
}

func (c cRMArticleCategoryDo) FirstOrCreate() (*model.CRMArticleCategory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CRMArticleCategory), nil
	}
}

func (c cRMArticleCategoryDo) FindByPage(offset int, limit int) (result []*model.CRMArticleCategory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cRMArticleCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cRMArticleCategoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cRMArticleCategoryDo) Delete(models ...*model.CRMArticleCategory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cRMArticleCategoryDo) withDO(do gen.Dao) *cRMArticleCategoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
