// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	CRMAdmin          *cRMAdmin
	CRMPermission     *cRMPermission
	CRMRole           *cRMRole
	CRMRolePermission *cRMRolePermission
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CRMAdmin = &Q.CRMAdmin
	CRMPermission = &Q.CRMPermission
	CRMRole = &Q.CRMRole
	CRMRolePermission = &Q.CRMRolePermission
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		CRMAdmin:          newCRMAdmin(db, opts...),
		CRMPermission:     newCRMPermission(db, opts...),
		CRMRole:           newCRMRole(db, opts...),
		CRMRolePermission: newCRMRolePermission(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CRMAdmin          cRMAdmin
	CRMPermission     cRMPermission
	CRMRole           cRMRole
	CRMRolePermission cRMRolePermission
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		CRMAdmin:          q.CRMAdmin.clone(db),
		CRMPermission:     q.CRMPermission.clone(db),
		CRMRole:           q.CRMRole.clone(db),
		CRMRolePermission: q.CRMRolePermission.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		CRMAdmin:          q.CRMAdmin.replaceDB(db),
		CRMPermission:     q.CRMPermission.replaceDB(db),
		CRMRole:           q.CRMRole.replaceDB(db),
		CRMRolePermission: q.CRMRolePermission.replaceDB(db),
	}
}

type queryCtx struct {
	CRMAdmin          ICRMAdminDo
	CRMPermission     ICRMPermissionDo
	CRMRole           ICRMRoleDo
	CRMRolePermission ICRMRolePermissionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CRMAdmin:          q.CRMAdmin.WithContext(ctx),
		CRMPermission:     q.CRMPermission.WithContext(ctx),
		CRMRole:           q.CRMRole.WithContext(ctx),
		CRMRolePermission: q.CRMRolePermission.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
